export { default as Nav } from './Nav'
export { default as Hero } from './Hero'
export { default as HowItWorks } from './HowItWorks'
export { default as Features } from './Features'
export { default as Pricing } from './Pricing'
export { default as Footer } from './Footer'
export { COPY } from './types'
export type { Lang } from './types'
